### ISSUE TITLE
Missing Dtool_BorrowThisReference

### ISSUE THREAD

**Issue by rdb** [WMOkiishi/types-panda3d#10]
Every interrogate-compiled module contains this function.

I had to add this to the bottom of every `panda3d-stubs/*/__init__.pyi`:
```python
def Dtool_BorrowThisReference(from_in, to_in) -> None: ...
```

**Comment by WMOkiishi** [comment]
Yeah, I noticed those, but I couldn't figure out what they were or how they were used. Do you know what the parameters to the function should be annotated as?

**Comment by rdb** [comment]
It takes two arbitrary instances of a C++ Panda type (ie. any DTOOL_SUPER_BASE subclass).  Don't know if those can be annotated specifically, I don't think you can directly access the DTOOL_SUPER_BASE type except through something like `TypedObject.__bases__[0]`.

**Comment by WMOkiishi** [comment]
Yeah, there's not a good way to annotate that at the moment, and it's probably not worth it for just these functions. I'll leave them without parameter annotations for now.
