### ISSUE TITLE
AsyncFuture.add_done_callback() is untyped

### ISSUE THREAD

**Issue by Moguri** [WMOkiishi/types-panda3d#11]
Neither the return value nor the `fn` argument are typed for `AsyncFuture.add_done_callback()` (found in core/_event.pyi).

Doing some digging, I suspect `PyObject*` types are being ignored and some logic may need to be added to use `Any` in these cases.

**Comment by WMOkiishi** [comment]
Yes, `PyObject*` types are output as untyped. I chose this instead of `Any` to signify that the types aren't necessarily unrepresentable by the type system. Does this cause issues? If so, I'd be willing to use `Incomplete` (an alias for `Any`) instead.

As far as this method in particular, do you know what types it accepts and returns at runtime? There is a system that makes it trivial to add/override types in the generated stubs.

**Comment by Moguri** [comment]
I had believed when Panda just takes a PyObject* it often actually meant Any/object (when it's not a callable). Although, I'm realizing that I'm just guessing without any actual data, so that assumption may be bad.

mypy doesn't like when untyped functions are used (may be only when using --strict). I figured Any would at least provided a typed function and better typing could be added to refine specific functions. However, this could probably hide some poor typing for a while, so maybe an error is better.

For add_done_callback(), the return type is None, and fn is a callable that takes an AsyncFuture as it's only argument and has a return type of None.

**Comment by WMOkiishi** [comment]
It seems to me that, while sometimes `PyObject*` parameters accept pretty much any Python object, they also often require sequences, types, or other specific kinds of objects in addition to callback functions.

Yeah, mypy only complains about that when using `--strict` (or just `--disallow-untyped-defs`). So maybe it would be best to just turn that rule off when checking Panda3D code. The [typeshed contribution guidelines](https://github.com/python/typeshed/blob/main/CONTRIBUTING.md#incomplete-annotations) don't have any preference between `Incomplete` and leaving things unannotated.

I can easily add those types to `add_done_callback()`. I'll close this issue when I've done so, and, if you'd like to continue the discussion about absent annotations, feel free to open a new issue.
