### ISSUE TITLE
RenderAttrib methods in derived classes should return Self instead of RenderAttrib

### ISSUE THREAD

**Issue by Moguri** [WMOkiishi/types-panda3d#12]
The various `RenderAttrib` derived classes (e.g., `ShaderAttrib`) have methods (e.g., `make()` and `set_flag()`) that return `RenderAttrib`. This is accurate per the supplied information from interrogate, but it is not ergonomic. For example, the following will raise type errors:

```python
attr = ShaderAttrib.make_default()
print(attr.has_shader()) # mypy assumes attr is of type RenderAttrib, which does not have has_shader()
```

The errors can be fixed by casting, but I wonder if some special cases should be added here to make things smoother.

**Comment by WMOkiishi** [comment]
This should be pretty simple to fix. Do you know why interrogate types them as `RenderAttrib` rather than the specific subclass? I would've guessed it was because they were inherited, but they don't seem to be.

**Comment by Moguri** [comment]
I do not know why they return the base class instead of the derived class. Maybe it makes some registration logic easier or something. It could also have just been an over sight that got copied enough to become a convention. I wonder if @rdb happens to know.

Assuming there isn't a technical reason for the return type, I wonder if the return types could be tightened up upstream. Changing return types would otherwise be an API break, but the returned values would be unchanged, so maybe that's okay?

**Comment by WMOkiishi** [comment]
I'll see if I can add something simple that modifies the return types of these functions. I did something similar with vector operations that also return `Self`. I also agree that an upstream change might make sense here.
