### ISSUE TITLE
Wrong return value for loader.loadSfx, loadMusic, and loadSound

### ISSUE THREAD

**Issue by Wizzerinus** [WMOkiishi/types-panda3d#13]
types-panda3d version: 0.3.3

The functions outlined above have their return value set to `_Callback | None`, which is only the case when the asynchronous loading is used, which is not the more common synchronous way to use these, which returns an AudioSound.

**Comment by WMOkiishi** [comment]
It should be simple to add overloads to these methods to differentiate between synchronous and asynchronous loading. I will do that.
