### ISSUE TITLE
Incorrect typehints for direct.interval.Track (?)

### ISSUE THREAD

**Issue by Wizzerinus** [WMOkiishi/types-panda3d#15]
version 0.3.3

Track works differently from other MetaIntervals: instead of accepting a list of intervals, it accepts a list of tuples(float time, interval) and starts each interval at the giving time. Types-panda3d currently does not know about this and still expects an interval during `__init__` and `append`.

**Comment by WMOkiishi** [comment]
This might call for making `MetaInterval` generic. Or I could just override the methods in `Track` and suppress mypy's complaints. Either way, it should be a simple fix.
