### ISSUE TITLE
GeomVertexWriter constructor can take a string as the second parameter

### ISSUE THREAD

**Issue by Maxwell175** [WMOkiishi/types-panda3d#3]
I've been using your typing for panda3d as it really helps out, but when using `GeomVertexWriter` I noticed that the typing indicates that an InternalName object is required as the second parameter while in reality a string can be used. This is because InternalName has an implicit constructor that takes an `std::string` causing an implicit conversion.

One possible way to solve this might be to check every class for possible implicit conversions using interrogate and combine them using a union.

**Comment by WMOkiishi** [comment]
First of all, thanks for the kind words.

> One possible way to solve this might be to check every class for possible implicit conversions using interrogate and combine them using a union.

This would be the way to do it, yes. Currently, a handful of implicit conversions are accounted for, but there's not yet a way to automatically account for all of them. This will be possible, however, in Panda3D 1.10.13. I've done some prototyping with preview builds, and will publish that functionality once 1.10.13 is released (which should be later this month, I believe).

Some technical details:
The prototype wasn't checking `make` methods, so this case was actually being overlooked, but that was an easy fix. Additionally, the specific wrapper allowing for coercion from a `str` to an `InternalName` actually expects a Python string in particular, so interrogate doesn't store that it requires anything more specific than a Python object. This means it will have to be special-cased in some way, but we already do that for supporting coercion of a `StrOrBytesPath` to a `Filename`, so it's not a big deal.

**Comment by WMOkiishi** [comment]
Fixed with https://github.com/WMOkiishi/types-panda3d/commit/49fe40eb0549083ff0384905daea3631c1b7660d.
(Despite what the commit message may say.)
