### ISSUE TITLE
I really loved this package

### ISSUE THREAD

**Issue by Legopapurida** [WMOkiishi/types-panda3d#5]
Please never stop your endeavors and keep your try to improve this package because this project and stubs for panda3d can help many developers to Improve in panda3d skills. 

Keep going and thanks for your efforts for developers in panda3d.

**Comment by Legopapurida** [comment]
I don't know how can I thank you but this is really useful for me.

**Comment by WMOkiishi** [comment]
> I don't know how can I thank you

You can find me in [the Panda3D Discord](https://discord.gg/UyepRMm) under the same name. I'd be happy to discuss this project further in its thread in the "projects" channel there. Thanks for the appreciation!
